### ISSUE TITLE
`dbt-meshify` split command, leaf nodes aren't made `public` when there are tests on the leaf nodes

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#121]
### Describe the bug

I am trying to do this:
![split_models](https://github.com/dbt-labs/dbt-meshify/assets/53586774/4b4a580b-c989-47a3-886c-a05b3a5fcb88)

So I ran:
```bash
dbt-meshify split sales_analytics --select +int_sales__unioned +int_returns__unioned transactions
```

I would expect `transactions` to be made `public` (because it’s a leaf node), but it's not.

### Steps to reproduce

- run `dbt-meshify split` on a selection of models that includes a leaf node

### Expected results

- leaf node made `public`

### Actual results

- lead node's access is unchanged

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by dave-connors-3** [comment]
howdy grace 👽 

I believe @nicholasyager tackled this in #102 !

1. I added a dummy leaf node to the `split_proj` project:
<img width="550" alt="image" src="https://github.com/dbt-labs/dbt-meshify/assets/73915542/b8dee52e-9f4d-4fd5-b659-b883988208e2">
2. ran `dbt-meshify --dry-run split test -s +orders dummy_leaf
3. Check out new project:

<img width="273" alt="image" src="https://github.com/dbt-labs/dbt-meshify/assets/73915542/d9e48d7e-b9e1-4ef1-a4b6-1347187244a8">


I think we should be good here!

**Comment by graciegoheen** [comment]
Hmm - I tried using my local dbt-meshify with the current branch and am still getting this bug:

- created a virtual environment
- pip installed dbt-core
- pip installed dbt-meshify
- navigated to my local dbt-meshify repo
- checked out the main branch
- `git pul`l
- ran `poetry install`
- navigated to my example project
- ran `dbt-meshify split sales_analytics --select +int_sales__unioned +int_returns__unioned transactions`

And still, my transactions model (leaf node) does not have a contract not is it's access changed to public

**Comment by graciegoheen** [comment]
Looks like this may be because I currently have tests on my transactions model. When I remove the tests and re-run the command, transactions is made public and a contract is added.

**Comment by nicholasyager** [comment]
>Looks like this may be because I currently have tests on my transactions model. When I remove the tests and re-run the command, transactions is made public and a contract is added.

Fantastic catch @graciegoheen! It sounds like we need to the graph grouping code to ignore test nodes as dependencies. Should be easy enough to resolve IMHO.
