### ISSUE TITLE
split should create all relevant dbt project files and folders

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#124]
Another thing I found odd here, was that only the folders that we're copying over are create. 

In my case, there was no empty folder for tests, seeds, macros, etc. that I'd expect when running a `dbt init`.

<img width="382" alt="Screenshot 2023-08-17 at 5 01 38 PM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/4156967a-216a-4288-9b6b-283df8675039">

_Originally posted by @graciegoheen in https://github.com/dbt-labs/dbt-meshify/issues/120#issuecomment-1683133612_

**Comment by nicholasyager** [comment]
Throwing my research notes and ideas in here as they pop up. I've identified the source of dbt-core's default project files in `dbt/include/starter_project`. My intention is to update the `DbtSubprojectCreator.write_project_file()` method to copy over the directory structure from here into the target project directory. Then, copy over a clean `dbt_project.yml` file and update it with the relevant configs from the parent project.

Open questions:
- Will pyyaml.rumel preserve comments?
- We may need to be mindful of the order of operations to prevent duplicate changes from firing (attempting to creating a directory twice)
