### ISSUE TITLE
connect command should not be case sensitive

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#126]
### Describe the bug

I tried to run the `dbt-meshify connect` command on two projects connected via the "source hack". 

I got this message:
![Screenshot 2023-08-18 at 2 20 19 PM](https://github.com/dbt-labs/dbt-meshify/assets/53586774/cfb9e846-4026-4a9d-92af-9b32473949f9)

After investigating, it was because my target schema in my upstream project was ALL CAPS which my source definition in my downstream project was lower case.

**Comment by dave-connors-3** [comment]
good eye goheen

**Comment by graciegoheen** [comment]
do all warehouses have case-insensitive database, schema, and table name?
