### ISSUE TITLE
connect command deletes ALL sources defined in the same yml file as the cross-project sources to remove

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#128]
### Describe the bug

I ran `dbt-meshify connect --project-paths . sales_analytics`.

My "source hack" sources are defined in the same yml file as my other sources. The entire file is removed, included the sources that should NOT have been removed.

<img width="1108" alt="Screenshot 2023-08-18 at 2 42 42 PM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/9d50f2ae-cdad-48c5-97f9-e71ddea4cced">

**Comment by dave-connors-3** [comment]
@graciegoheen I think this was logic that was reworked in @nicholasyager's changes. My old logic definitely had this logic to "delete the source file if there are no other tables in the source definition", and at the moment, the tables are deleted, but the top level source info is not deleted (see #131 )

as it stands, the new logic would only delete files via the `RawFileManager.delete_file()` method, which isn't called anywhere at the moment!

**Comment by graciegoheen** [comment]
Now I seem to get a new error when running that command!
<img width="835" alt="Screenshot 2023-08-21 at 10 54 59 AM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/e9b069a6-0642-4430-9a4e-2eda94702f29">

**Comment by nicholasyager** [comment]
Ha! In that invocation, `connect` must be returning `None` early since there are no dependencies found, which blows up the change set processor. I'll make a different ticket to track.

**Comment by graciegoheen** [comment]
Ah yep - no dependencies found because I forgot about the capitalization issue. Ran it again (with all caps schema name in my sources yml file), and am getting the following:
<img width="851" alt="Screenshot 2023-08-21 at 11 00 47 AM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/c16d67cd-4e7f-4efe-b8b8-9fc749882211">
It's... better for sure! But I think the ideal would be removing the entire sources block for `source: barnold_corp` rather than just setting `tables: []`.

**Comment by graciegoheen** [comment]
Great - let's close this one out then!
