### ISSUE TITLE
`require-dbt-version` improperly handled on a split

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#138]
### Describe the bug

splitting a project with `require-dbt-version` doesn't properly parse the semantic version into the new project

<img width="300" alt="image" src="https://github.com/dbt-labs/dbt-meshify/assets/73915542/11e9c9a7-bf39-462a-ac29-819df5a01c06">

### Steps to reproduce

1. define a `require-dbt-version`
2. perform a split
3. observe `require-dbt-version` in newly created project

### Expected results

settings in both projects are equivalent

### Actual results

broke

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by nicholasyager** [comment]
l
o
o
k
s

f
i
n
e

t
o

m
e
!
