### ISSUE TITLE
create method for generating a boilerplate dbt Project to clone

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#14]
- should we use `cookiecutter` ?
- should we shell to the `dbtRunner` and call dbt init? (i don't think so)
- do we use the `starter_project` that ships in core

**Comment by nicholasyager** [comment]
@dave-connors-3 I second your doubt regarding using `dbt init` to spin up new projects. I was able to mock up a simple version of this last night, and it had a number of unpleasant edge cases (like need a profile).
