### ISSUE TITLE
Check if split command copies over files with doc blocks

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#158]
🤔 Some low risk thoughts
- `split` doesn't copy over all project files, so there may be documentation that's not copied over (like markdown files).
  - Now that I'm thinking about it, does split copy over files with docblocks?
- `group` and `create-group` will update existing groups already defined in yml.

_Originally posted by @nicholasyager in https://github.com/dbt-labs/dbt-meshify/pull/115#discussion_r1312985891_

**Comment by dave-connors-3** [comment]
did a little poking at docs blocks:

- models that depend on docs blocks move just fine
- there's not any evidence in the manifest that i can see that ties a given `manifest.docs` entry with `manifest.nodes` entries -- i am quite curious how core currently resolves and compiles docs blocks! i think until we know how that relationship is established, we won't be able to correctly move docs blocks unless we did something hacky like copy over any docs blocks that share paths with the other selected files (assuming people follow structure best practices)
