### ISSUE TITLE
Add a `--version` flag

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-meshify#200]
### Describe the feature

```
$ dbt-meshify --version
```

or:

```
$ dbt-meshify -v
```

Gives the same output as:

```shell
python -m pip show dbt-meshify
```

### Additional context
Is this feature dbt Core or dbt Cloud specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

**Comment by nicholasyager** [comment]
Hi @dbeatty10 👋🏻 Quick clarifying question: 

When you say

> Gives the same output as:
> ```
> python -m pip show dbt-meshify
> ```

You are referring to the package version number, correct? Presumably there isn't a desire to be outputting the other package details too 😁

**Comment by dbeatty10** [comment]
I wasn't precise in my original description 😬 

You got it @nicholasyager -- just the package version number.

#201 looks great 🚀
