### ISSUE TITLE
`--owner name dave` seems odd

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-meshify#65]
### Describe the feature
Adding name/email to groups has a bit of an odd syntax today: `--owner name dave` to assign the name `dave`. Is this following some CLI convention?

My initial feel is that `--owner-name dave` or `--owner "name:dave"` would seem more appropriate, but I might be wrong 😄

**Comment by dave-connors-3** [comment]
i agree the name dave is odd
