### ISSUE TITLE
preserve quotes in YML

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#66]
### Describe the bug

Our YAML provider seems to be dropping quotes from string properties:

<img width="789" alt="image" src="https://github.com/dbt-labs/dbt-meshify/assets/73915542/30c93d11-83b9-46c6-bb4c-d05c4d194c06">

### Steps to reproduce

1. have some strings in a yml file
2. run an operation that interacts with that yml file
3. check the formatting of the string object

### Expected results

No YML should be edited that isn't directly related to the feature set being invoked by the package

### Actual results

Errant YAML edits!

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: 🦆 )

**The output of `dbt debug`:**
```
❯ dbt debug
15:15:21  Running with dbt=1.5.1
15:15:21  dbt version: 1.5.1
15:15:21  python version: 3.10.10
15:15:21  python path: /Users/daveconnors/dev/sandbox/dbt-meshify-demo/.venv/bin/python3
15:15:21  os info: macOS-13.2.1-arm64-arm-64bit
15:15:21  Using profiles.yml file at /Users/daveconnors/dev/sandbox/dbt-meshify-demo/profiles.yml
15:15:21  Using dbt_project.yml file at /Users/daveconnors/dev/sandbox/dbt-meshify-demo/dbt_project.yml
15:15:21  Configuration:
15:15:21    profiles.yml file [OK found and valid]
15:15:21    dbt_project.yml file [OK found and valid]
15:15:21  Required dependencies:
15:15:21   - git [OK found]

15:15:21  Connection:
15:15:21    database: jaffle_shop
15:15:21    schema: analytics
15:15:21    path: ./reports/jaffle_shop.duckdb
15:15:21    Connection test: [OK connection ok]

15:15:21  All checks passed!
```

### Are you interested in contributing the fix?
yes!

[should be fairly easy!](https://stackoverflow.com/questions/39262556/preserve-quotes-and-also-add-data-with-quotes-in-ruamel)

**Comment by dave-connors-3** [comment]
this test still runs properly with the edited yml, but IMO we should strive not to edit anything that we don't intend to

**Comment by b-per** [comment]
This looks straightforward: https://stackoverflow.com/questions/42094599/preserving-quotes-in-ruamel-yaml
