### ISSUE TITLE
allow `grouper.py` to add access and groups separately 

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#67]
per convo, we'll need a way to get the `access` logic without adding a new group

**Comment by nicholasyager** [comment]
@dave-connors-3 I don't recall the specific use case we were hoping to unblock for this. Can you add some additional context on this issue?

**Comment by dave-connors-3** [comment]
This was a request to separate the code paths for adding `access` and `group` parameters to model yml separately, so that the `split` command could adjust `access` without needing to also set a `group` -- I worked around this in my PR with a pretty naive refactor -- should be able to close this once that gets merged!

**Comment by nicholasyager** [comment]
@dave-connors-3 Perfect! This is enough for me to go on 👍🏻
