### ISSUE TITLE
better exception handling for dbtRunner

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#7]
I think something like this would work:

```python
    def get_subproject_resources(self, subproject_selector: str) -> List[str]:
        ls_results = self.dbt_operation(["--log-level", "none", "ls", "-s", subproject_selector])

        if not ls_results.success:
            raise ls_results.exception

        return ls_results.result
```

Given that this would be common code, there's a good argument for having exception handling performed within the `dbt_operation` method.

_Originally posted by @nicholasyager in https://github.com/dbt-labs/dbt-meshify/pull/5#discussion_r1171677718_

**Comment by nicholasyager** [comment]
Resolved as part of #22!
