### ISSUE TITLE
rollback on failed command

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#71]
### Describe the bug

if a meshify command fails, it should roll back anything it did 

### Steps to reproduce

run 
```
> dbt group group_name -s orders
(without owner)
```

see that the parse fails, and some files changed despite the failure

### Expected results

nothing in the event of a failed commans

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by nicholasyager** [comment]
@dave-connors-3 With the implementation of change sets, is this a failure mode that we need to worry about any more?
