### ISSUE TITLE
Default create-group with nothing selected, makes a group with all of your models

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#77]
### Describe the bug

When I run `dbt-meshify operation create-group raw_vault`, dbt-meshify creates a new group with _all_ of my project's models in it. I would expect that when I don't specify selector syntax, dbt-meshify would create a new _empty_ group.

Thoughts?

**Comment by dave-connors-3** [comment]
I think this could be a reasonable enhancement! groups should be a subset of your DAG, not the whole damn thing!
