### ISSUE TITLE
When a model has no yml, and is marked as private -> extra yml configs

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#78]
### Describe the bug

When I execute a `create-group` command, and dbt-meshify creates _new_ yaml for a private model - it creates extra "config" and "columns" blank fields:
<img width="1018" alt="Screen Shot 2023-06-26 at 11 26 41 AM" src="https://github.com/dbt-labs/dbt-meshify/assets/53586774/a8235dd7-1bc7-47a7-818e-0872f6a87837">

```
dbt-meshify operation create-group raw_vault 
```

**Comment by dave-connors-3** [comment]
hey Grace! I believe I encountered this when developing #63 and made an edit to the function that filters out empty dictionary items to also filter out`[]` or `{}` 

[in main](https://github.com/dbt-labs/dbt-meshify/blob/main/dbt_meshify/storage/yaml_editors.py#L15)
[in my pr](https://github.com/dbt-labs/dbt-meshify/blob/split-command/dbt_meshify/storage/file_content_editors.py#L15)

**Comment by dave-connors-3** [comment]
worked locally for me on the split command branch!

<img width="925" alt="image" src="https://github.com/dbt-labs/dbt-meshify/assets/73915542/5e4cf2d4-1ab9-40be-a819-777c197e4a72">
