### ISSUE TITLE
enhance logging UX

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#92]
### Describe the feature

From review of #73, we have some room for improvement for logging UX

1. more specific error types 
2. UX for setting log levels

let's improve it! 

### Who will this benefit?

users, log enthusiasts

### Are you interested in contributing this feature?

sure

**Comment by dave-connors-3** [comment]
@nicholasyager was this resolved with #94 ? We may still need some UX for log levels?

**Comment by nicholasyager** [comment]
> @nicholasyager was this resolved with #94 ? We may still need some UX for log levels?

@dave-connors-3 We do have better exceptions as part of #94, but we _do_ need to add log level configuration of some sort still.

**Comment by nicholasyager** [comment]
Given all the improvements we've made on exception handling and logging as of 0.4.0, I' think we're good to close this. Thoughts, @dave-connors-3?

**Comment by nicholasyager** [comment]
I'm going to say that we're in a "pretty good" state for now. We can revisit this if we receive feedback that our logging needs additional tuning.
