### ISSUE TITLE
Better docs / example use cases

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#99]
### Describe the feature

From feedback from the devex team, our docs could use some work! 

We should add more documentation and example use cases, so that users have a clear understanding of "where/how to get started".

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

New users of dbt-meshify!

**Comment by graciegoheen** [comment]
@dave-connors-3 feel free to add any extra info based on your convos with the devex folks!

**Comment by nicholasyager** [comment]
@graciegoheen Am I correct in assuming that you've achieved this task as part of your docs mega PR?

**Comment by graciegoheen** [comment]
Yep, let's close it!
